name: GCP OIDC – read secret
on:
  workflow_dispatch:

permissions:
  id-token: write    # REQUIRED for OIDC
  contents: read

env:
  GCP_PROJECT: gcp-labs-z5woyhds
  WIP_PROVIDER: projects/44705150860/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider
  TARGET_SA: iam-lab-7-target@gcp-labs-z5woyhds.iam.gserviceaccount.com

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP via OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIP_PROVIDER }}
          service_account: ${{ env.TARGET_SA }}
          project_id: ${{ env.GCP_PROJECT }}
          # These are the *valid* v2 options if you want ADC set up automatically:
          create_credentials_file: true
          export_environment_variables: true
          # (Do NOT use 'activate_credentials_file' — it doesn't exist in v2.)

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 474.0.0'

      - name: Verify caller
        run: |
          gcloud auth list
          gcloud config get-value account
          gcloud config set project "$GCP_PROJECT"

      - name: Read secret
        run: |
          SECRET_ID="flag-iam-7"
          gcloud secrets versions access latest --secret="$SECRET_ID" --project="$GCP_PROJECT"
